### ISSUE TITLE
it seems to be no GPU Core load in it

### ISSUE THREAD

**Issue by heyuhengmatt** [ts-korhonen/LibreHardwareMonitorAfterburnerPlugin#1]
I can't setup to find the gpu core load from this

**Comment by ts-korhonen** [comment]
Hi,

What is the model of your GPU and can you see the core load in [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/latest)?

**Comment by ts-korhonen** [comment]
The duplicated names are treated as the same sensor source in Afterburner and only one can be selected at a time. Unfortunately Afterburner only distinguishes sensors by their name.

I've created a quick fix by adding a running number to the name when it's a duplicate. This is a compromise that separates the sensors, but keeps the name short. This can be found in the [latest release](https://github.com/ts-korhonen/LibreHardwareMonitorAfterburnerPlugin/releases/latest).

I'm planning to make a sensor renaming feature and individual selection in the setup and thus improve this aspect further.

**Comment by heyuhengmatt** [comment]
Thanks a lot, this immediately help with the problem.
And so expecting your new feature on plan~XD
