### ISSUE TITLE
Vcore in afterburner not showing to the thousandths decimal place

### ISSUE THREAD

**Issue by PsiloCA** [ts-korhonen/LibreHardwareMonitorAfterburnerPlugin#3]
As the title suggests I am only able to see the whole number 1. am i missing a setting in Afterburner somewhere?

**Comment by ts-korhonen** [comment]
Thank you for noticing this! The values are given to Afterburner with even higher precision than that, but they seem to be rounded or truncated to integers in Afterburner. I'll investigate the issue and see if there's anything that can be done in the plugin side to fix this.

**Comment by ts-korhonen** [comment]
The cause was Afterburner plugin interface defaulting to zero decimals and was fixable by setting the format for each sensor type. Voltage now has three decimal format in the [latest release](https://github.com/ts-korhonen/LibreHardwareMonitorAfterburnerPlugin/releases/latest).
